In [1]:
library(dplyr)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [2]:
df <- read.csv('../log.csv')

In [3]:
sem_espera <- df %>% filter(t_espera == 0)
sem_espera

  i medico t_inicio  t_saida  t_espera t_chegada
1 1 3       72.86174 1138.833 0         72.86174
2 2 1       96.08762 1169.406 0         96.08762
3 3 2      233.26359 1301.301 0        233.26359

In [4]:
df <- df %>% filter(t_espera > 0)
df %>% head()

  i medico t_inicio t_saida  t_espera  t_chegada
1 4 3      1138.833 2309.092  777.6341 361.1990
2 5 1      1169.406 2318.665  693.5573 475.8484
3 6 2      1301.301 2355.658  699.5659 601.7350
4 7 3      2309.092 3481.215 1463.6786 845.4129
5 8 1      2318.665 3424.440 1440.0991 878.5661
6 9 2      2355.658 3362.189 1378.3410 977.3167

In [5]:
get.in.line <- df %>% select(medico, t_chegada)

In [6]:
get.in.line <- get.in.line %>% mutate(line_1 = ifelse(medico == 1, +1, 0)) %>% 
mutate(line_2 = ifelse(medico == 2, +1, 0)) %>% mutate(line_3 = ifelse(medico == 3, +1, 0)) %>% select(-medico)

In [7]:
get.in.line

    t_chegada line_1 line_2 line_3
1    361.1990 0      0      1
2    475.8484 1      0      0
3    601.7350 0      1      0
4    845.4129 0      0      1
5    878.5661 1      0      0
6    977.3167 0      1      0
7   1147.7356 0      1      0
8   1165.2142 1      0      0
9   1232.7478 0      0      1
10  1330.2817 0      1      0
11  1437.7055 1      0      0
12  1525.5243 0      0      1
13  1668.9015 0      1      0
14  1709.7817 1      0      0
15  1852.1904 0      0      1
16  1913.6898 0      1      0
17  1916.8243 1      0      0
18  2032.4944 0      0      1
19  2199.1871 0      1      0
20  2284.6230 1      0      0
21  2286.6057 0      0      1
22  2388.1277 0      1      0
23  2608.3924 1      0      0
24  2763.6423 0      0      1
25  2891.4026 0      1      0
26  3450.5504 1      0      0
27  3480.6650 0      0      1
28  3513.5710 0      1      0
29  3759.2234 1      0      0
30  3764.5578 0      0      1
... ...       ...    ...    ...
194 22281.48  1      0      0
195 22365.04  0      1      0
196 22494.57  0      0      1
197 22528.54  1      0      0
198 22548.71  0      1      0
199 22569.32  0      0      1
200 22659.41  0      1      0
201 22699.39  1      0      0
202 22820.09  0      0      1
203 23141.62  0      1      0
204 23260.34  1      0      0
205 23595.68  0      0      1
206 23640.49  1      0      0
207 23647.83  0      1      0
208 24001.84  0      0      1
209 24046.91  0      1      0
210 24053.64  1      0      0
211 24162.38  0      0      1
212 24165.24  0      1      0
213 24277.41  1      0      0
214 24317.40  0      0      1
215 24431.92  0      1      0
216 24541.83  1      0      0
217 24607.72  0      0      1
218 24715.76  0      1      0
219 24840.34  1      0      0
220 24852.67  0      0      1
221 25090.37  0      1      0
222 25120.97  1      0      0
223 25158.33  0      0      1

In [8]:
get.out.line <- df %>% select(medico, t_inicio)

In [9]:
get.out.line <- get.out.line %>% mutate(line_1 = ifelse(medico == 1, -1, 0)) %>% 
mutate(line_2 = ifelse(medico == 2, -1, 0)) %>% mutate(line_3 = ifelse(medico == 3, -1, 0)) %>% select(-medico)

In [10]:
get.out.line

    t_inicio  line_1 line_2 line_3
1    1138.833  0      0     -1
2    1169.406 -1      0      0
3    1301.301  0     -1      0
4    2309.092  0      0     -1
5    2318.665 -1      0      0
6    2355.658  0     -1      0
7    3362.189  0     -1      0
8    3424.440 -1      0      0
9    3481.215  0      0     -1
10   4289.546  0     -1      0
11   4429.902 -1      0      0
12   4521.151  0      0     -1
13   5273.953  0     -1      0
14   5550.623 -1      0      0
15   5675.873  0      0     -1
16   6365.851  0     -1      0
17   6552.662 -1      0      0
18   6728.463  0      0     -1
19   7340.087  0     -1      0
20   7673.108 -1      0      0
21   7890.598  0      0     -1
22   8348.969  0     -1      0
23   8581.325 -1      0      0
24   8820.300  0      0     -1
25   9449.099  0     -1      0
26   9566.050 -1      0      0
27   9772.614  0      0     -1
28  10533.557  0     -1      0
29  10659.567 -1      0      0
30  10851.889  0      0     -1
... ...       ...    ...    ...
194 68262.53  -1      0      0
195 68451.24   0     -1      0
196 69230.79   0      0     -1
197 69350.61  -1      0      0
198 69394.00   0     -1      0
199 70190.00   0      0     -1
200 70380.43   0     -1      0
201 70544.64  -1      0      0
202 71237.78   0      0     -1
203 71429.83   0     -1      0
204 71549.45  -1      0      0
205 72199.13   0      0     -1
206 72561.55  -1      0      0
207 72586.85   0     -1      0
208 73177.32   0      0     -1
209 73529.57   0     -1      0
210 73760.45  -1      0      0
211 74290.97   0      0     -1
212 74511.04   0     -1      0
213 74744.51  -1      0      0
214 75443.95   0      0     -1
215 75573.72   0     -1      0
216 75895.30  -1      0      0
217 76529.34   0      0     -1
218 76659.11   0     -1      0
219 76921.26  -1      0      0
220 77522.54   0      0     -1
221 77711.18   0     -1      0
222 77854.97  -1      0      0
223 78652.04   0      0     -1

In [11]:
names(get.in.line) <- c("t", "line_1", "line_2", "line_3")

In [12]:
names(get.out.line) <- c("t", "line_1", "line_2", "line_3")

In [13]:
t_df <- rbind(get.in.line, get.out.line) %>% arrange(t)

In [14]:
t_df

    t         line_1 line_2 line_3
1    361.1990  0      0      1
2    475.8484  1      0      0
3    601.7350  0      1      0
4    845.4129  0      0      1
5    878.5661  1      0      0
6    977.3167  0      1      0
7   1138.8331  0      0     -1
8   1147.7356  0      1      0
9   1165.2142  1      0      0
10  1169.4057 -1      0      0
11  1232.7478  0      0      1
12  1301.3009  0     -1      0
13  1330.2817  0      1      0
14  1437.7055  1      0      0
15  1525.5243  0      0      1
16  1668.9015  0      1      0
17  1709.7817  1      0      0
18  1852.1904  0      0      1
19  1913.6898  0      1      0
20  1916.8243  1      0      0
21  2032.4944  0      0      1
22  2199.1871  0      1      0
23  2284.6230  1      0      0
24  2286.6057  0      0      1
25  2309.0915  0      0     -1
26  2318.6652 -1      0      0
27  2355.6577  0     -1      0
28  2388.1277  0      1      0
29  2608.3924  1      0      0
30  2763.6423  0      0      1
... ...       ...    ...    ...
417 68262.53  -1      0      0
418 68451.24   0     -1      0
419 69230.79   0      0     -1
420 69350.61  -1      0      0
421 69394.00   0     -1      0
422 70190.00   0      0     -1
423 70380.43   0     -1      0
424 70544.64  -1      0      0
425 71237.78   0      0     -1
426 71429.83   0     -1      0
427 71549.45  -1      0      0
428 72199.13   0      0     -1
429 72561.55  -1      0      0
430 72586.85   0     -1      0
431 73177.32   0      0     -1
432 73529.57   0     -1      0
433 73760.45  -1      0      0
434 74290.97   0      0     -1
435 74511.04   0     -1      0
436 74744.51  -1      0      0
437 75443.95   0      0     -1
438 75573.72   0     -1      0
439 75895.30  -1      0      0
440 76529.34   0      0     -1
441 76659.11   0     -1      0
442 76921.26  -1      0      0
443 77522.54   0      0     -1
444 77711.18   0     -1      0
445 77854.97  -1      0      0
446 78652.04   0      0     -1

In [15]:
t_df %>% mutate(line_1 = cumsum(line_1)) %>%
        mutate(line_2 = cumsum(line_2)) %>%
        mutate(line_3 = cumsum(line_3))

    t         line_1 line_2 line_3
1    361.1990 0      0      1
2    475.8484 1      0      1
3    601.7350 1      1      1
4    845.4129 1      1      2
5    878.5661 2      1      2
6    977.3167 2      2      2
7   1138.8331 2      2      1
8   1147.7356 2      3      1
9   1165.2142 3      3      1
10  1169.4057 2      3      1
11  1232.7478 2      3      2
12  1301.3009 2      2      2
13  1330.2817 2      3      2
14  1437.7055 3      3      2
15  1525.5243 3      3      3
16  1668.9015 3      4      3
17  1709.7817 4      4      3
18  1852.1904 4      4      4
19  1913.6898 4      5      4
20  1916.8243 5      5      4
21  2032.4944 5      5      5
22  2199.1871 5      6      5
23  2284.6230 6      6      5
24  2286.6057 6      6      6
25  2309.0915 6      6      5
26  2318.6652 5      6      5
27  2355.6577 5      5      5
28  2388.1277 5      6      5
29  2608.3924 6      6      5
30  2763.6423 6      6      6
... ...       ...    ...    ...
417 68262.53  9      10     10
418 68451.24  9       9     10
419 69230.79  9       9      9
420 69350.61  8       9      9
421 69394.00  8       8      9
422 70190.00  8       8      8
423 70380.43  8       7      8
424 70544.64  7       7      8
425 71237.78  7       7      7
426 71429.83  7       6      7
427 71549.45  6       6      7
428 72199.13  6       6      6
429 72561.55  5       6      6
430 72586.85  5       5      6
431 73177.32  5       5      5
432 73529.57  5       4      5
433 73760.45  4       4      5
434 74290.97  4       4      4
435 74511.04  4       3      4
436 74744.51  3       3      4
437 75443.95  3       3      3
438 75573.72  3       2      3
439 75895.30  2       2      3
440 76529.34  2       2      2
441 76659.11  2       1      2
442 76921.26  1       1      2
443 77522.54  1       1      1
444 77711.18  1       0      1
445 77854.97  0       0      1
446 78652.04  0       0      0